### ISSUE TITLE
Current release not compatible with react-redux@^6.x.x or react-redux@^7.x.x

### ISSUE THREAD

**Issue by code-forger** [americanexpress/iguazu#3]
Since react-redux has upgraded to the new React Context API ([React Redux v6.0.0](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0)), ConnectAsync does not receive the redux store from context, and the following error is thrown.

`Uncaught TypeError: Cannot read property 'dispatch' of undefined`

**Comment by mtomcal** [comment]
We definitely need to release a new major version of Iguazu with updates to consume new Context from the latest React Redux. We have this effort scheduled in our backlog for Nov/Dec but we would love any PR contribution ahead of schedule if you're willing. 👍

**Comment by mtomcal** [comment]
@code-forger We released an RC version of Iguazu v3 that has all these updated dependencies as promised. `npm i iguazu@3.0.0-0` Let us know what you think.
